### ISSUE TITLE
Modularisation of code and automated tested

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/pyw#1]
Discuss how to write modular code and how to test it (we will also need to cover basic cli).

This will concentrate on making code easier to debug and potentially lead to using testing frameworks such as pytest (although not necessarily).

**Comment by Nikoleta-v3** [comment]
This should include `debugging`

**Comment by drvinceknight** [comment]
Closing based on: https://github.com/drvinceknight/pyw/tree/master/wks/2019-01-10

Note I also opened #11.
